version: "0.2"
runson: android
autosplit: true
concurrency: 1
jobLabel: [ 'high', 'Android', 'Appium']
retryOnFailure: true
maxRetries: 2

runtime:
  language: node
  version: "18"

pre:
  - npm install
  - npx playwright install
cacheKey: '{{ checksum "package-lock.json" }}'
cacheDirectories:
  - node_modules
testDiscovery:
    command: cat pw_androidtests.txt
    mode: static
    type: raw
testRunnerCommand: npm run test-android --verbose


framework:
  name: appium
  args:
    playwrightRD : true
    region: eu


env:
  INFRA_TIMEOUT: 2000
